#!/bin/sh

CONFIG=btorconfig.h

:>$CONFIG

cat<<EOF >>$CONFIG
/**********************************************************/
/* Automatically generated by './mkconfig': do note edit! */
/**********************************************************/
EOF

echo "#define BTOR_CC \"$1\"" >>$CONFIG
echo "#define BTOR_CFLAGS \"$1\"" >>$CONFIG

echo "#define BTOR_OS \"`uname -srmn`\"" >>$CONFIG
echo "#define BTOR_COMPILED \"`date`\"" >>$CONFIG
cat<<EOF >>$CONFIG
#define BTOR_RELEASED "Fri Mar  4 19:52:48 CET 2011"
#define BTOR_VERSION "1.4.1"
#define BTOR_ID "376e6b097a9a63af246339a13dd0e61b8774db77"
EOF
