#!/bin/sh

CONFIG=precocfg.hh

:>$CONFIG

cat<<EOF >>$CONFIG
/***************************************************************/
/* Automatically generated by './gen_config.sh': do note edit! */
/***************************************************************/
EOF

echo "#define PRECOSAT_CXX \"$1\"" >>$CONFIG
echo "#define PRECOSAT_CXXFLAGS \"$1\"" >>$CONFIG

echo "#define PRECOSAT_OS \"`uname -srmn`\"" >>$CONFIG
echo "#define PRECOSAT_COMPILED \"`date`\"" >>$CONFIG
cat<<EOF >>$CONFIG
#define PRECOSAT_RELEASED "Thu Jan 12 07:59:44 CET 2012"
#define PRECOSAT_VERSION "576"
#define PRECOSAT_ID "7e5e66faa15ff83953915cba4b46afe851cd5847"
EOF
